// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Why Do I Like Soccer?",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Why Do I Like Soccer?",
            targets: ["AppModule"],
            bundleIdentifier: "ssc2026henriquels.ssc2026henriquels",
            teamIdentifier: "2DK23BZ7KB",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .sportsGames
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
